"""Independent Python reference for PaperType ink seed algorithm v1 (docs/05 §2.1).

Generates fixtures/ink-seed-v1.json. The TypeScript implementation is tested
against this file, so it must stay independent of the TS code.
"""
import json
import os
import unicodedata

M = 0xFFFFFFFF


def fnv1a32(s: str) -> int:
    h = 0x811C9DC5
    for b in s.encode('utf-8'):
        h ^= b
        h = (h * 0x01000193) & M
    return h


def imul(a: int, b: int) -> int:
    return (a * b) & M


def mulberry32(seed: int):
    state = seed & M

    def nxt() -> int:
        nonlocal state
        state = (state + 0x6D2B79F5) & M
        t = imul(state ^ (state >> 15), 1 | state)
        t = ((t + imul(t ^ (t >> 7), 61 | t)) & M) ^ t
        return (t ^ (t >> 14)) & M

    return nxt


def draws(seed: int, n: int = 3):
    r = mulberry32(seed)
    return [r() for _ in range(n)]


def graphemes(paragraph: str):
    """Minimal grapheme splitter sufficient for the fixture texts below:
    combining marks, ZWJ sequences, variation selectors and emoji modifiers
    attach to the previous cluster. (Real implementations use Intl.Segmenter /
    ICU BreakIterator; fixture texts avoid cases where those could differ.)"""
    out = []
    attach_next = False
    for ch in paragraph:
        cp = ord(ch)
        joins = (
            unicodedata.category(ch) in ('Mn', 'Me')
            or cp == 0x200D
            or 0xFE00 <= cp <= 0xFE0F
            or 0x1F3FB <= cp <= 0x1F3FF
        )
        if out and (joins or attach_next):
            out[-1] += ch
        else:
            out.append(ch)
        attach_next = cp == 0x200D
    return out


def glyph_seeds(ink_seed: str, text: str):
    result = []
    for p, para in enumerate(text.split('\n')):
        o = 0
        for g in graphemes(para):
            if not g.isspace():
                c = ord(g[0])
                key = f"v1:{ink_seed}:{p}:{o}:{c}"
                seed = fnv1a32(key)
                result.append({"grapheme": g, "p": p, "o": o, "c": c, "key": key,
                               "seed": seed, "u": draws(seed)})
            o += len(g)  # Python str length == code point count
    return result


fixture = {
    "description": "Test vectors for PaperType ink seed algorithm v1 (docs/05_RENDER_AUDIO_HAPTIC.md §2.1). "
                   "u = the first three raw mulberry32 outputs as unsigned 32-bit integers; r = u / 2^32. "
                   "Generated by an independent Python reference implementation.",
    "seedAlgorithmVersion": 1,
    "fnv1a32": [
        {"input": s, "hash": fnv1a32(s)} for s in ["", "a", "foobar", "v1:x:0:0:97", "한글"]
    ],
    "mulberry32": [
        {"seed": s, "u": draws(s, 5)} for s in [0, 1, 0xDEADBEEF, 0xFFFFFFFF]
    ],
    "texts": [
        {"inkSeed": "2a54a12a-5a75-4f0b-a437-18c353bd86c5", "text": t,
         "glyphs": glyph_seeds("2a54a12a-5a75-4f0b-a437-18c353bd86c5", t)}
        for t in [
            "Hello, typewriter.",
            "오늘은 종이 위에\n천천히 적어 본다.",
            "값 닭 읽다",
            "café → cafe\u0301",
            "😀한 \U0001F469\u200D\U0001F4BB글",
            "\n\n빈 줄 뒤",
        ]
    ],
}

# Standard FNV-1a 32 vectors (http://www.isthe.com/chongo/tech/comp/fnv/) as a self-check.
assert fnv1a32("") == 0x811C9DC5
assert fnv1a32("a") == 0xE40C292C
assert fnv1a32("foobar") == 0xBF9CF968

out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "fixtures", "ink-seed-v1.json")
os.makedirs(os.path.dirname(out), exist_ok=True)
with open(out, "w", encoding="utf-8", newline="\n") as f:
    json.dump(fixture, f, ensure_ascii=False, indent=2)
    f.write("\n")
print("glyphs:", sum(len(t["glyphs"]) for t in fixture["texts"]))
